version: "3.7"
services:
  sqlserver:
    build:
      context: ./build
      dockerfile: Dockerfile
    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1433:1433"
    container_name: sqlserver
    hostname: mssql
    volumes:
      - type: volume
        source: mssqluser
        target: /var/opt/sqlserver
      - type: volume
        source: mssqlsystem
        target: /var/opt/mssql
      - type: bind
        source: ./backups
        target: /var/opt/mssql/data/backups

volumes:
  mssqluser:
    name: mssqluser
  mssqlsystem:
    name: mssqlsystem
